version: "3"
services:
  container-db:
    image: postgres:12
    restart: always
    container_name: postgres12
    environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=postgres
    - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
    - "5442:5432"
    volumes:
    - "./db-data:/var/lib/postgresql/data/pgdata"
    - "./db-backup:/var/lib/postgresql/db-backup"

