apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-centos
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.104
  share: /tmp/nfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1