version: "3"
services:
  mysql-db:
    image: mysql:8.0
    restart: always
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
     MYSQL_ROOT_PASSWORD: 'password'
    ports:
    - "3306:3306"
    volumes:
    - "./db-data:/var/lib/mysql"
    - "./db-backup:/var/lib/backup"