apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-1-4
  namespace: deploy-4
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25.1
          ports:
          - protocol: TCP
            containerPort: 80

        - name: multitool
          image: wbitt/network-multitool:latest
          ports:
          - protocol: TCP
            containerPort: 1180
          env:
            - name: HTTP_PORT
              value: "1180"

---
apiVersion: v1
kind: Service
metadata:
  name: svc1-4-1
  namespace: deploy-4
spec:
  selector:
    app: nginx
  ports:
    - name: nginx
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: multitool
      protocol: TCP
      port: 9002
      targetPort: 1180
  type: ClusterIP

---
apiVersion: v1  # Сервис для задания № 2
kind: Service
metadata:
  name: svc-nodeport
  namespace: deploy-4
spec:
  selector:
    app: nginx
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      nodePort: 30001
    - name: multitool
      protocol: TCP
      port: 1180
      nodePort: 30002
  type: NodePort


---
apiVersion: v1
kind: Pod
metadata:
  name: multitool
  namespace: deploy-4
  labels:
    cont: multitool
spec:
  containers:
    - name: multitool
      image: wbitt/network-multitool:latest
      ports:
      env:
        - name: HTTP_PORT
          value: "8080"
