apiVersion: v1
kind: Namespace
metadata:
  name: deploy-7
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: deploy-7
spec:
  storageClassName: nfs-centos
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nfs
  namespace: deploy-7
  labels:
    app: multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool:latest
          volumeMounts:
          - name: nfs
            mountPath: /tool
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: my-pvc