apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool-backend
  namespace: deploy-5
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool:latest
          ports:
          - protocol: TCP
            containerPort: 1180
          env:
            - name: HTTP_PORT
              value: "1180"

---
apiVersion: v1
kind: Service
metadata:
  name: svc-backend
  namespace: deploy-5
spec:
  selector:
    app: backend
  ports:
    - name: multitool
      protocol: TCP
      port: 1180
      targetPort: 1180
  type: ClusterIP