apiVersion: v1
kind: Namespace
metadata:
  name: deploy-8

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config2
  namespace: deploy-8
data:
  ports_nginx: '80'
  index: |
    <H1> Test page 2 HTTPS!</h1>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-8-2
  namespace: deploy-8
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25.1
          volumeMounts:
          - name: configmap-nginx
            mountPath: /usr/share/nginx/html/
          env:
          - name: NGINX_PORT
            valueFrom:
                configMapKeyRef:
                  name: test-config2
                  key: ports_nginx
      volumes:
        - name: configmap-nginx
          configMap:
            name: test-config2
            items:
              - key: "index"
                path: "index.html"

---
apiVersion: v1
kind: Service
metadata:
  name: svc8
  namespace: deploy-8
spec:
  selector:
    app: nginx
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-deploy-8
  namespace: deploy-8
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: kuber-5.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc8
                port:
                  number: 80
  tls:
    - hosts:
       - kuber-5.local
      secretName: crt

---
apiVersion: v1
kind: Secret
metadata:
  name: crt
  namespace: deploy-8
data:
  tls.crt: |
    TUlJRm5UQ0NBNFdnQXdJQkFnSVVhMWhnVUdyZU4wZ1FlS0hSSmNYYVgyUVR1eXN3RFFZSktvWklodmNOQVFFTApCUUF3WGpFTE1Ba0dBMVVFQmhNQ1VsVXhEREFLQmdOVkJBZ01BMDFUU3pFTU1Bb0dBMVVFQnd3RFRWTkxNUTR3CkRBWURWUVFLREFWTWIyTmhiREVMTUFrR0ExVUVDd3dDVUVNeEZqQVVCZ05WQkFNTURXdDFZbVZ5TFRVdWJHOWoKWVd3d0hoY05Nak14TWpBME1EZ3pNelV6V2hjTk1qUXhNakF6TURnek16VXpXakJlTVFzd0NRWURWUVFHRXdKUwpWVEVNTUFvR0ExVUVDQXdEVFZOTE1Rd3dDZ1lEVlFRSERBTk5VMHN4RGpBTUJnTlZCQW9NQlV4dlkyRnNNUXN3CkNRWURWUVFMREFKUVF6RVdNQlFHQTFVRUF3d05hM1ZpWlhJdE5TNXNiMk5oYkRDQ0FpSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0lQQURDQ0Fnb0NnZ0lCQUszSFFaSTBzSUpYbkFwS1RIRDcyTXZ4RWF3VUpHQUpuNEpoZ0gveAozUWlFZFhUM1ZZSzdkdDNPOGpGY1kwclFxeFhuRkFPUGI2dUZMbFRPVVFrZkNMM0xoRDh6WUkyQnY3UExYenBuCmZtalEzYk9BNHVkMkk4UC9YYzQ0ODNWRW9CbGJyVGVIaGtBczY2Q2VWeXBudGhiV2R2THB4OU9MM0JSMHVwVlIKZHhEd0FxSVRJcWFPYmVnOWlzV2dLSWhWSHJMZyt5Z2tQSFJ2dzl3U25HTE8ycjk0L2xxSTdKZXo0NEV0M2tzKwpueFZwY1hrUkcwSTJuaGliZG5zTDJpcTdQNkc3eWtmaGE5RGhRWnNIRFd5VXZ4MHYxUksycld3NlcyeWF3SlkyCkQ3SXpLWE40NVRzWTNSVUNqTDZGcTRLWThhazBDV1hydnMwSmdoZm13U0h2eDRWWXFiTGZaZEFPa0pBTVZjOTMKRlhBMzlEY3hjYjlPNHMzWVJLWEJjRTV3ajMwQ0xnMUVhWXljWFBOL2lXM3puL2NJallHZ1NicnZMRy8zWjVYcAo3T2l2WU5VQkFLRW9uSXIzdklnWGtmb25xc2xId0IyVjNXb1FXczZDbnVBNEtRdWFPclZuZ3krQUhwOGYrN3JiCkdZZzNBMlZGVDVBcXl3TThnR3Y1bE41cFBRZTA5aGhCeXYvM0pVYlJybUZuQ3RZZXJZRHhxc0tYNzl4bFovM1MKNnA3TE0wcjAvOUZtcUd4U0FFKzNTSzY3M2NWSXJuOFBDZ2JtNFEvenIrYlR2emtjVmx2enJWNGR0VGtucE9iOApqbEJvZk9ORDhndDc2ZzIyL2pka2tjbGlaQlZ6V1NIYk1xcmc3WitjVmxWbnp1cHVhQkduaURDY1ZQSi9scDJYCnEzZWRBZ01CQUFHalV6QlJNQjBHQTFVZERnUVdCQlJlUFZaWXo0NEhKeXBpT3ZYN1VwWVJSSDJOQ2pBZkJnTlYKSFNNRUdEQVdnQlJlUFZaWXo0NEhKeXBpT3ZYN1VwWVJSSDJOQ2pBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQnpyTHBQZXpsd2JkR1E3RjlhMERWVjhaNXZjRFppd0VaQ0htVjdmRlBHCk8rOFNzYzAvWkxHNUZNSTJjWUpqRm9WZDB5akY0MUExdWV5TGF5a1J5R3p4WDhnR2lBVXB2NjZmdG1xaC9XNEMKSmI0U1ZQWXp0U3ZrR0t6cnNONEZnV2E0QTVCcS9sK3FYV1BqRDVzZlUzTThtUGNJZVZrV05RdnJ0REZTdE5ITgp0Y3VzbUV5MDdUV0pabEhYbzFVekVnVUFmcGNTRDRpLzRielR3Yjd1NExCeFlNWE9rQ2k3V01NakE2dUhrWTdOClJRYjdQYm5SekM5cnZlUHlSWHpXWVpHb1V2WGMvZWc4OERTaytlOTA1RXQzWEVWZ0NPNEZvT1BZUFREajhzNEsKQTA1dXF6eDNlck1ETDBBell5WXhiZzJCTk51azVJWjRud3FNWndXVS9VWExGT1dDS0RSZkwrd0NxTVVSSThUcApHTjEyZXV2UG5GNlM5aGV0Y3k2VDdSY1JSTW5FSjdZWHdIUjY3aHpEd0dwZ0txekhUNWxzWHhJWmhWR3BqblVNCnE3dWpNWXNvRFJhcldkS2RmeTBsSEhnaUFxWUxmNDBFMUU1Yk9lTUtlQmcxTHdFZmUveGpCazkvR0dzbUdMQ0QKelVMYThVdXlRUURCVFpGdlZJeG5JM1FyeHhGdHYyTVJGSEhyMWREcG9lRXk2VTFvNWlTMmgyaXhNalhYWkVlYQpwV3UzaTB1MWVEVjlZcVpNclJEcjR0czY4emV0UHJtR3lCbWhwN0crUWE3cDFoUk41dlc0a1VPNzNEbEFucEZkCkI1Y1pvdDc0TllXOHA1cVpkTERJQ2FUbTI2bEUvUWNndERGbjcrSGFqRmpUSEhDbklLdTNLRHpEaUd4Z2hqNGYKa0E9PQo=
  tls.key: |
    TUlJSlF3SUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NDUzB3Z2drcEFnRUFBb0lDQVFDdHgwR1NOTENDVjV3SwpTa3h3KzlqTDhSR3NGQ1JnQ1orQ1lZQi84ZDBJaEhWMDkxV0N1M2JkenZJeFhHTkswS3NWNXhRRGoyK3JoUzVVCnpsRUpId2k5eTRRL00yQ05nYit6eTE4NlozNW8wTjJ6Z09MbmRpUEQvMTNPT1BOMVJLQVpXNjAzaDRaQUxPdWcKbmxjcVo3WVcxbmJ5NmNmVGk5d1VkTHFWVVhjUThBS2lFeUttam0zb1BZckZvQ2lJVlI2eTRQc29KRHgwYjhQYwpFcHhpenRxL2VQNWFpT3lYcytPQkxkNUxQcDhWYVhGNUVSdENOcDRZbTNaN0M5b3F1eitodThwSDRXdlE0VUdiCkJ3MXNsTDhkTDlVU3RxMXNPbHRzbXNDV05nK3lNeWx6ZU9VN0dOMFZBb3kraGF1Q21QR3BOQWxsNjc3TkNZSVgKNXNFaDc4ZUZXS215MzJYUURwQ1FERlhQZHhWd04vUTNNWEcvVHVMTjJFU2x3WEJPY0k5OUFpNE5SR21NbkZ6egpmNGx0ODUvM0NJMkJvRW02N3l4djkyZVY2ZXpvcjJEVkFRQ2hLSnlLOTd5SUY1SDZKNnJKUjhBZGxkMXFFRnJPCmdwN2dPQ2tMbWpxMVo0TXZnQjZmSC91NjJ4bUlOd05sUlUrUUtzc0RQSUJyK1pUZWFUMEh0UFlZUWNyLzl5VkcKMGE1aFp3cldIcTJBOGFyQ2wrL2NaV2Y5MHVxZXl6Tks5UC9SWnFoc1VnQlB0MGl1dTkzRlNLNS9Ed29HNXVFUAo4Ni9tMDc4NUhGWmI4NjFlSGJVNUo2VG0vSTVRYUh6alEvSUxlK29OdHY0M1pKSEpZbVFWYzFraDJ6S3E0TzJmCm5GWlZaODdxYm1nUnA0Z3duRlR5ZjVhZGw2dDNuUUlEQVFBQkFvSUNBQW5WWHlnRFZFT2o2b0FJa1VmSmNJeWwKMFE2d094aTJJckVSakdCeEVzVmpIWFJuZEk3SHhlT3FUTGt2VmEwTG5zckgvekZ1WWU3T1EvOW5oMTFoUkxEYwp2ZGlIc3p4K3JaYmllTHFJMWJYZnI5UHpCS1A5WXV1NTNSaUl6M29BenFCd3VCNE96TEYvK1R0bkNsNnJiTG5oCkcrMEYvcGxCYmt3NENNRGZVY0lER3RzS0F5bHlvTlNGK3Y3UTM4cExLc2dMaEJyUzVocmVvakluV1hNYjZuUHcKU0ZCZU5Da25kRVhBanpZcHpuMjdNRUVlRHpGUmZ1TzhsRmxGSSt6TUdMOHhyYklnbHVYRWdWNWc2VWtPSjd4aQprd2VTajhDeWtxN1VHUGJIQzE5Vmx0QmlkSEpDSjJ5RGJ1eHZDdlFDYkpaYkMvY1kvbnlDdjdwVGcvVkVLTUdTCmV2R2NhTE42Ym85VU1GZlNKaHRpS0JHdWVTYzNhWUlhNFdMaFBwZ1lETzJvY2hjQ0xpaGE2UWNLVTR1OW43b2oKeUhxb1EwRG51NU5qSlZIMGU3L2lKNlNzZjFid282WHNHNGJOMEN1ZHNhdGVtempUZU00ajFFOGR0UHRXdlpuagpnRUlDcWJnS0tVK3Q1cEViL2VOVDhIVkZMczFLellueFE0akR6SjBoNDBzVVVYVVdENmtrQzJScFJNcU00bWY1CkVINWlkOWU2OXBMUGlVU3FoOTlpRFFhbW1FSlJGWE0vQUlSVXhSVlhPU210TTBnb2NIbXJaUG1QeVRjTGhaN2IKZmlMVEs1MlplcDhNNjBkZ1lreWF3eitpOVdpUFo0L3g3WGtjRUhSTFdpOElhNjZpZnZSTi9oYzlIOTM1U1k2bApMVnhLQ2dxUE1pTVkxTiswalBMZkFvSUJBUURtTzlRRThyb1ZZQXBKblFocVg0VjJaTXNJbWQ0K3NKb2NDTEdECkszcG1HTEt4SkRjSDhvSDJpcXluNFRiY0w3UXdYU1NRa3dwaHVHaXgrcnpXeFphUVJYb0pUdlRuM1EvSWZsV0sKbjJnKzRWc2hMSlpzcENBZ1dmajJXRE9MWnhJZlNTNS9QdWdOU0c0eFRqdDhXcEFBTWQrczdwWjJXeWdrRzZ2WQpBeW8vMWRrTXlPODNZWVYxZkgzTXQ2U2hsTUxHOVorU0pMTlFXSEtBTUdXK1lsdFlCakFuZ1IrRFdlMjBucExMCjVrNmlkc2M1THd5OUc3ZTBpeUx1M3RTWEZGMFVuMVBRWGQ1djZZNUFpUDcyK3FUN3kxazRHR0JuQWR5U1RBSzkKOFRqQXIwYjFvcnFXcTUxRkN3Q1V4VjdDRTZIRnhhOEdhVmpWN2Y0cE1vTEsyckUzQW9JQkFRREJPZnpiZHFZUQp5NTNFSUFNYldaN3hPcW9DRHpxRnZWM2FCWUZtM0ZPOHpaVDI3N1pCb1g0elJmRGYrQ1hrSnFnQ0ZSRG5aK29GCmY2K3d5YmkvWHU4allvbW9ORkZPZXA1eENGd1ZZMmZHaHlnUXluSk01MDZvSlZycCtuWW82ZFN1RE81c2xTSnMKQTFCS3lEWXhrTXp4b1VvZG1sZHc3OG1Ca0RRTGhiSjRhZWxHQXlsclI0azYrRDRWalR5UndxUHQ1WXd4SjJldgp6b1FFRVlKOHpPTEhINm9SUVRIWTFINm5EL3VVVjdQWXdVSEJKcVlDT2RKQ25lMkV2dTJINWp2d3VtMUgrRXRoCnRXYzNLV3A2ZDlFS3Y4MFBpbEQ1b2FjdnRrOTNlWktMR2FzU040NUt6WjIvbmFUSFhFbE5CbTJrbUh0UWtzNjMKTTYzVEtuWXEweGZMQW9JQkFRRFZlOHA0SUI0ZUxlUzhKNGtqSVptZWs0MlVWeUMySG9sM3p6UFNmaUZMeEVFRgpjcUE0bFV5Zk1DMHlxZWwxdUNJcjZtSTZVSzRDdUwwVHMzMGc1U3hjY0ovZE84SnBzUml1Zno2UWdJbG9MUXlVCk1VVDJUaVdmK2UyWmQyV3NNSkdrUXZhRGRQQTFTT0VzaE84eHVzUGwrbGorZ0dreUxBcUhtTVQ2VXN6OVRpeXAKNXpPeHRaTEx3dmpmTjdYSFFpcHQxRm4zYUdLQThOS1RQTTFMQU9iVU0wQzVrTWlJd24xZ3l0MHhoa2VKNi91RgpjYlF0TWlOZ25OZHlpVnExRUdQUytIMytLdHhVQjB3cFdSNmFJd1dTbVJjTXBjWFdIZXJLR1FNOTN3d1IxelZFCkZYVlF1cWJrMjNQWmZ6NERWYkxlc1JRL0xMWDhBR2Q1Q2VZdmRTTjNBb0lCQUdQLzI3SEVwTXNhWmFyRG1uZ0UKR0xMbFZtaThjdUFXRWNVc2hqeXltQStsSVl2dW9SYzBPYmpWWUlTNHl2dFpXaWZCdVQ3WlU0N0c5eWo2TE1lMQpuUE5tSXJIUGFhakE0dERDcjgxTjViNGo0b05XRW5Oa1hodTlRV0RJQTNESEd3OThsOFBRSnNGWnNhc1NGS0h3Ck8zQnR0WXErZnJSdkZJMGVFU0ZKYndUTVl6S2Rua2pyKzhSdUJzdG1qY3N0dldMNEltYXA2d3BjU1l4RmQ0K1oKQldCaUxjVENSY2JlcWpGUm56UzFjdGtob3lNUUdtZ2Fmb3VGYWhBQ003SGFZSGtFTWx4Rnp0VmhhV3B0MzdKRAo0Z2E3SHFnRlFFVUErU0pES3JzOVNxNzhlTUZ6eVF0RGdIbFRYNXpoVVBvdzhudDFncFEvZGdYd0UreXVFL3V6CnhhTUNnZ0VCQUpTSWNmVXB5NitncTgvNkpVcXVmWW1DbHFlUGZ0bXV4L3F4Y2FrZE9wczlPUDl6TmM2WDUxa2YKZmNkRTg0M1grNUVYajd5b0wwc0tmdjIxbmM3NkJOa3JydDFCcVpJQ0dUcTh1RmZWRkIzdXVFUk9wV1YzenVuVQplVTJ2Rlc3SVhaZVNxMnZPT2l0REhCNjh3clJoaUhQWkMzRFZGTlJNbC9udit3cWFyNXZmS0NwN0lkUnVvOCtLCkNmT2RRY2haU1VISVppei9sb3IzbzNPcFJvM1YwdlVKaXdGTHMwWEQwQnZuRlc3a2dvT1EyVUlxQXdVbkRaY3kKQnVxTk5pVmZUc3p1TmxpN3I4VmFxWC9TRVNmYkprYUh5NXpyNGlIN0VoVlg0ckpKc1FyaXBjR25XeVg5RzB5cAp4OXozQ1I2VGlHK0F5VnJqbVVIZnBCbHJ1Y0gwTXJRPQ==
type: kubernetes.io/tls